name: bot_main_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc:
  cloud_firestore: ^4.8.0
  convex_bottom_bar: ^3.2.0
  equatable: ^2.0.5
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  firebase_crashlytics: ^3.3.2
  firebase_storage: ^11.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.0
  flutter_polyline_points: ^1.0.0
  flutter_svg: ^2.0.6
  geolocator: ^9.0.2
  get_it: ^7.6.0
  go_router: ^7.1.1
  google_maps_flutter: ^2.2.8
  google_sign_in: ^5.4.4
  http: 
  image_picker: ^0.8.7+5
  intl: ^0.18.0
  permission_handler: ^10.3.0
  shimmer_animation: ^2.1.0+1
  toggle_switch: ^2.1.0
  validators: ^3.0.0
  video_player: ^2.6.1
  

dev_dependencies:
  bloc_test:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/bus_images/
    - assets/icons/
    - assets/videos/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
