// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABqiSdj-vLG-tLJ6fVN9kdwivTstJJZlI',
    appId: '1:1017991836538:web:d22edf344eb2b00eb0dcc3',
    messagingSenderId: '1017991836538',
    projectId: 'fb-auth-bloc-d1201',
    authDomain: 'fb-auth-bloc-d1201.firebaseapp.com',
    storageBucket: 'fb-auth-bloc-d1201.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsI9H1SPoxQbepb61-LuOtBgfphgGcYmI',
    appId: '1:1017991836538:android:99187e4aa1e72517b0dcc3',
    messagingSenderId: '1017991836538',
    projectId: 'fb-auth-bloc-d1201',
    storageBucket: 'fb-auth-bloc-d1201.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQY900CUko2JTQV2idWz2SeUZuTSaCeyo',
    appId: '1:1017991836538:ios:1f6421a500eb1cf4b0dcc3',
    messagingSenderId: '1017991836538',
    projectId: 'fb-auth-bloc-d1201',
    storageBucket: 'fb-auth-bloc-d1201.appspot.com',
    iosClientId: '1017991836538-q54r0m2hh3m5hu96k1i2n27e4ufnrkkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.bot-main-app',
  );
}
